// AUTH
http://localhost:3000
POST /auth/register
{
  "email": "bkristiqn7@gmail.com",
  "username": "teriola",
  "password": "123456",
  "rePassword": "123456"
}
http://localhost:3000
POST /auth/login
{
  "email": "bkristiqn7@gmail.com",
  "password": "123456"
}

// TRANSACTIONS
http://localhost:3000
x-authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjA1ZGExMzExYjRjYjgxNzU0YjhhZDYiLCJlbWFpbCI6ImJrcmlzdGlxbjdAZ21haWwuY29tIiwiaWF0IjoxNzExNjY1NTg1fQ.eYVeMu82zpjs2W0y6NFGfXw_Ura9-g52vvo_gWWpkQI
POST /transactions/create
{
  "type": "income",
  "currency": "BGN",
  "category": "salary",
  "amount": 1000
}
